# PyTorchのテンソル（tensor）の扱い方

このノートブックでは、PyTorchのテンソルを扱う際に少し分かりにくいメソッドなどについて解説します。

## PyTorch の `gather` メソッド

`torch.gather` は、「**インデックスのテンソルを使って、元のテンソルから値を抜き出す**」ための関数です。

- **書式**: `torch.gather(input, dim, index)`
  - **`input`**: 元のテンソル
  - **`dim`**: どの次元に沿って要素を取り出すか（0 や 1 などの整数）
  - **`index`**: 取り出したい位置を示すテンソル
- **重要なポイント**
  - `index` の形状は、**出力の形状と同じ**になります。
  - `index` は、`input` と同じ形状か、少なくとも `dim` 以外の次元については同じ形状である必要があります。

強化学習では、Q 値テーブル `q_values` から「実際に選んだ行動の Q 値だけを抜き出す」ときなどによく使われます。

In [3]:
import torch

# 入力テンソル（例）: 2 行 3 列
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])

# dim=1（列方向）に沿って値を取り出したいとする
# 各行ごとに「どの列を取り出すか」を index で指定する
index = torch.tensor([
    [2, 1],  # 1 行目からは列 2 と列 1 を取り出す
    [0, 0]   # 2 行目からは列 0 と列 0 を取り出す
])

# gather によって、index で指定した位置の値を集める
out = torch.gather(x, dim=1, index=index)

print("x =")
print(x)
print("\nindex =")
print(index)
print("\nout = torch.gather(x, dim=1, index=index) =")
print(out)

# 強化学習でのイメージ例
# q_values: 各状態ごとの行動価値（バッチサイズ=3, 行動数=4）
q_values = torch.tensor([
    [1.0, 2.0, 3.0, 4.0],
    [0.5, 1.5, 2.5, 3.5],
    [10.0, 20.0, 30.0, 40.0]
])

# 各状態で実際に選んだ行動（例）
actions = torch.tensor([2, 0, 3])  # 0〜3 の整数

# gather を使うために、actions を 2 次元に変形（列ベクトル）
actions_2d = actions.view(-1, 1)  # shape: (batch, 1)

# dim=1（行動の次元）で、選んだ行動の Q 値だけを抜き出す
chosen_q_values = torch.gather(q_values, dim=1, index=actions_2d)

print("\nq_values =")
print(q_values)
print("\nactions =")
print(actions)
print("\nactions_2d =")
print(actions_2d)
print("\nchosen_q_values =")
print(chosen_q_values)  # shape: (batch, 1)

x =
tensor([[10, 20, 30],
        [40, 50, 60]])

index =
tensor([[2, 1],
        [0, 0]])

out = torch.gather(x, dim=1, index=index) =
tensor([[30, 20],
        [40, 40]])

q_values =
tensor([[ 1.0000,  2.0000,  3.0000,  4.0000],
        [ 0.5000,  1.5000,  2.5000,  3.5000],
        [10.0000, 20.0000, 30.0000, 40.0000]])

actions =
tensor([2, 0, 3])

actions_2d =
tensor([[2],
        [0],
        [3]])

chosen_q_values =
tensor([[ 3.0000],
        [ 0.5000],
        [40.0000]])
