# PyTorch テンソル連結入門：`torch.cat` 徹底理解

**目的**: 複数のテンソルを、指定した次元 (`dim`) に沿って「くっつける（連結する）」関数。

- **書式**: `torch.cat(tensors, dim=0)`
- **引数**:
  - **`tensors`**: テンソルのリストやタプル（例: `[t1, t2, t3]`）
  - **`dim`**: どの次元方向に連結するか（0 が行方向、1 が列方向、など）
- **条件**:
  - `dim` 以外の次元サイズは、すべてのテンソルで一致している必要があります。

### `cat` という名前の由来

`cat` は英単語の「猫」ではなく、**concatenate（連結する）** の略です。

- **concatenate**: 「つなげる」「連結する」という意味の英単語
- `torch.cat` = 「テンソルを連結する関数」という名前

同様に、NumPy の `np.concatenate` も同じ語源で、配列を連結する関数です。

### よく出るイメージ

2 次元テンソル（行列）を例にします。

- **`dim=0`**: 行方向に縦につなげる（行が増える）
- **`dim=1`**: 列方向に横につなげる（列が増える）

`torch.stack` との違い:
- `torch.cat`: 既存の次元を「伸ばす」→ 形状の次元数は増えない
- `torch.stack`: 新しい次元を追加する → 形状の次元数が 1 つ増える

In [2]:
import torch

# 基本例: 1 次元テンソルを連結
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print("x =", x)
print("y =", y)

z = torch.cat([x, y], dim=0)
print("torch.cat([x, y], dim=0) =", z)
print("shape:", z.shape)  # → torch.Size([6])

x = tensor([1, 2, 3])
y = tensor([4, 5, 6])
torch.cat([x, y], dim=0) = tensor([1, 2, 3, 4, 5, 6])
shape: torch.Size([6])


In [3]:
import torch

# 2 次元テンソルの例（行・列方向の連結）
A = torch.tensor([[1, 2],
                  [3, 4]])
B = torch.tensor([[5, 6],
                  [7, 8]])

print("A =\n", A)
print("B =\n", B)

# dim=0: 行方向（縦）に連結 → 行数が増える
C0 = torch.cat([A, B], dim=0)
print("\ntorch.cat([A, B], dim=0) =\n", C0)
print("shape:", C0.shape)  # → torch.Size([4, 2])

# dim=1: 列方向（横）に連結 → 列数が増える
C1 = torch.cat([A, B], dim=1)
print("\ntorch.cat([A, B], dim=1) =\n", C1)
print("shape:", C1.shape)  # → torch.Size([2, 4])

A =
 tensor([[1, 2],
        [3, 4]])
B =
 tensor([[5, 6],
        [7, 8]])

torch.cat([A, B], dim=0) =
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
shape: torch.Size([4, 2])

torch.cat([A, B], dim=1) =
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
shape: torch.Size([2, 4])


In [4]:
import torch

# 3 つ以上のテンソルを連結する例
A = torch.tensor([[1, 2],
                  [3, 4]])
B = torch.tensor([[5, 6],
                  [7, 8]])
D = torch.tensor([[ 9, 10],
                  [11, 12]])

C_multi = torch.cat([A, B, D], dim=0)
print("3 つ以上のテンソルを連結 (dim=0) =\n", C_multi)
print("shape:", C_multi.shape)

3 つ以上のテンソルを連結 (dim=0) =
 tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])
shape: torch.Size([6, 2])


In [5]:
import torch

# torch.stack との違いを確認
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

S = torch.stack([x, y], dim=0)
print("stack の例: torch.stack([x, y], dim=0) =\n", S)
print("shape:", S.shape)  # → torch.Size([2, 3])  新しい次元が増える

stack の例: torch.stack([x, y], dim=0) =
 tensor([[1, 2, 3],
        [4, 5, 6]])
shape: torch.Size([2, 3])
